---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

We r going to make some plotly plots.

## Load packages and data
```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

lets get the data...
```{r}
data("nyc_airbnb")

nyc_airbnb=
  nyc_airbnb %>% 
  mutate(rating=review_scores_location / 2) %>% 
  select(
    borough=neighbourhood_group,neighbourhood,price,room_type,lat,long,rating) %>% 
  filter(
    borough=="Manhattan",
    room_type=="Entire home/apt",
    price %in% 100:500
  ) %>% 
  drop_na(rating)
```
Lets make a scatterplot!
```{r}
nyc_airbnb %>%
  mutate(text_label = str_c("Neighboorhood: ", neighbourhood, "\nPrice: $", price, "\nRating: ", rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long, 
    type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
```
Boxplots?
```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```
bar plot?
```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```
## ggplotly...(extremely slow)
```{r}
scatter_ggplot = 
  nyc_airbnb %>%
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = 0.25) +
  coord_cartesian()

ggplotly(scatter_ggplot)
```








